language: ruby
env:
  - USE_OFFICIAL_GEM_SOURCE=1

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server
  - elasticsearch

rvm:
  - 2.3.0

before_install:
  - "bundle config --global github.https true"

before_script:
  - psql -c "CREATE USER \"macintosh1\" WITH CREATEDB PASSWORD '12345678';" -U postgres
  - psql -c "create database \"rails365_test\" WITH OWNER=\"macintosh1\";" -U postgres
  - cp config/settings.yml.example config/settings.yml
  - cp config/database.yml.example config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate

script: RAILS_ENV=test bundle exec rake
